### ISSUE TITLE
Failed node-pre-gyp install --fallback-to-build on 32 Ubuntu 14.04 - "error: ‘apply_visitor’ is not a member of ‘mapnik::util’"

### ISSUE THREAD

**Issue by matkoniecz** [mapnik/node-mapnik#473]
after https://github.com/kosmtik/kosmtik/issues/69 and 

```
sudo apt-get install libprotobuf-dev protobuf-compiler
```

mapnik build failed again

```
make: Entering directory `/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/build'
  ACTION binding_gyp_make_vector_tile_target_generate_protoc_files Release/obj/gen/vector_tile.pb.cc
  ACTION binding_gyp_make_vector_tile_target_generate_setting Release/obj/gen/mapnik_settings.js
  COPY /home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/lib/binding/node-v11-linux-ia32/mapnik_settings.js
  TOUCH Release/obj.target/make_vector_tile.stamp
  CXX(target) Release/obj.target/vector_tile/gen/vector_tile.pb.o
  AR(target) Release/obj.target/vector_tile.a
  COPY Release/vector_tile.a
  CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
In file included from ../src/mapnik_logger.cpp:1:0:
../src/utils.hpp: In function ‘void node_mapnik::params_to_object(v8::Local<v8::Object>&, const string&, const value_holder&)’:
../src/utils.hpp:86:34: error: ‘apply_visitor’ is not a member of ‘mapnik::util’
     ds->Set(NanNew(key.c_str()), mapnik::util::apply_visitor(value_converter(), val));
                                  ^
../src/utils.hpp:86:34: note: suggested alternative:
In file included from /usr/include/boost/variant/apply_visitor.hpp:18:0,
                 from /usr/include/mapnik/value.hpp:35,
                 from ../src/utils.hpp:17,
                 from ../src/mapnik_logger.cpp:1:
/usr/include/boost/variant/detail/apply_visitor_delayed.hpp:81:41: note:   ‘boost::apply_visitor’
 inline apply_visitor_delayed_t<Visitor> apply_visitor(Visitor& visitor)
                                         ^
make: *** [Release/obj.target/mapnik/src/mapnik_logger.o] Error 1
make: Leaving directory `/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/build'
```

**Comment by springmeyer** [comment]
closing per https://github.com/kosmtik/kosmtik/issues/69

**Comment by pnorman** [comment]
How does kosmtik/kosmtik#69 fix this issue?

**Comment by denaje** [comment]
I am on 64-bit Arch Linux and get this error as well.

**Comment by denaje** [comment]
Update: I _think_ I fixed this problem by downgrading nodejs from 5.0.0 to 0.12.7. I also installed mapnik globally after downgrading (which worked), and then `npm install` worked for me.

**Comment by aberenyi** [comment]
I can confirm that downgrading node to `0.12.7` solves the issue on Arch x64. It is quite annoying tho.

**Comment by strk** [comment]
Should this be reopened ? The error arises when trying to build  mapnik as part of tilelive-bridge `npm install`
