### ISSUE TITLE
Script to install node-mapnik breaking on its own

### ISSUE THREAD

**Issue by pnorman** [mapnik/node-mapnik#429]
We are installing a specific node-mapnik version by specifying the hash, as we're using unreleased mapnik and can't depend on everything working with arbitrary versions. We also needed a node-mapnik more recent than tagged upstream.

This worked to install a couple of weeks ago, but no longer does

```sh
NODE_MAPNIK_HASH=39a9cdefe182be41d39e64d03f51d33cb12fb348
echo "Running Mapnik $(mapnik-config --version) (git $(mapnik-config --git-revision))"
echo "Running $(g++ --version | head -n1)"
sed -i "s|\"mapnik\":.*|\"mapnik\": \"git+https://github.com/mapnik/node-mapnik.git#$NODE_MAPNIK_HASH\",|" package.json

npm install --build-from-source
```

```
Running Mapnik 3.0.0-pre (git f688b206f831ed427d3a92f64b51df2d7b99b48b)
Running g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Installing node-mapnik 39a9cdefe182be41d39e64d03f51d33cb12fb348
> mapnik@3.2.0 install /data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'wrappy'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:336:15)
gyp ERR! stack     at Function.Module._load (module.js:278:25)
gyp ERR! stack     at Module.require (module.js:365:17)
gyp ERR! stack     at require (module.js:384:17)
gyp ERR! stack     at Object.<anonymous> (/data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/npm/node_modules/inflight/inflight.js:1:76)
gyp ERR! stack     at Module._compile (module.js:460:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
gyp ERR! stack     at Module.load (module.js:355:32)
gyp ERR! stack     at Function.Module._load (module.js:310:12)
gyp ERR! stack     at Module.require (module.js:365:17)
gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
gyp ERR! command "/data/servers/mq_nms/stdbase/bin/node" "/data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/mapnik
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v1.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/data/servers/mq_nms/stdbase/bin/node /data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
node-pre-gyp ERR! command "node" "/data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/mapnik
node-pre-gyp ERR! node -v v0.11.16
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/data/servers/mq_nms/stdbase/bin/node /data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (7)
npm ERR! Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! argv "/data/servers/mq_nms/stdbase/bin/node" "/data/servers/mq_nms/stdbase/bin/npm" "install" "--build-from-source"
npm ERR! node v0.11.16
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! mapnik@3.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.2.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/servers/mq_jenkins_mapping/jobs/kosmtik/workspace/npm-debug.log
```

How can we install node-mapnik in a way that will continue to work with a given version of Mapnik?

**Comment by springmeyer** [comment]
This is a bizarre error. It seems to be caused by `Cannot find module 'wrappy'`. But that module is not a depedency of node-mapnik, nor node-mapniks build dependencies (node-pre-gyp and node-gyp) that I know of.

Overall I see you are using `node v0.11.16` which is the unstable series and not recommended. I'm going to close this issue as I don't think it is related to node-mapnik.

**Comment by pnorman** [comment]
> Overall I see you are using node `v0.11.16` which is the unstable series and not recommended.

What is recommended? My recollection is that 0.12.x doesn't work with Kosmtik, which specifies 1.4.16, which is the latest version of node-mapnik which works with a released mapnik.

My concern isn't this particular error, my concern is that a working build went to a non-working build without any changes, even with a locked down node-mapnik version

**Comment by springmeyer** [comment]
0.10.x is recommended. Do you think that will work with Kosmtik?

**Comment by pnorman** [comment]
I suspect so, the only real dependencies of Kosmtik are some basic libraries, node-mapnik, and carto.

I think all we're using node/npm for right now is Kosmtik, node-mapnik, Mapbox Studio, and carto.
