### ISSUE TITLE
error: no matching function for call to ‘range_by_section

### ISSUE THREAD

**Issue by strk** [mapnik/node-mapnik#611]
Attempts to --build-from-source fail here with:
```
/usr/include/boost/geometry/algorithms/detail/overlay/get_turns.hpp:177:60: error: no matching function for call to ‘range_by_section(const mapnik::geometry::multi_line_string<double>&, const boost::geometry::section<boost::geometry::model::box<mapnik::geometry::point<double> >, 2ul>&)’
         cview_type1 cview1(range_by_section(geometry1, sec1));
                                                            ^
```
I'm building on an Ubuntu 14.04.4 LTS with boost 1.54.0

**Comment by strk** [comment]
The failing build is with npm 2.11.3 and node 0.10.40.

The build succeeds on an Ubuntu 14.04.03 LTS with npm 1.4.3 and node 0.10.26 (same boost)

**Comment by strk** [comment]
Same error when upgrading npm to 3.8.1 (keeping node 0.10.40 and the usual boost).
Installed mapnik is from the pgraster-resample branch, if that matters (https://github.com/mapnik/mapnik/pull/3348)

**Comment by flippmoke** [comment]
https://github.com/mapnik/node-mapnik/issues/612
