### ISSUE TITLE
Windows: build with node@4.2.1

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/node-mapnik#542]
@springmeyer @flippmoke 

Builds fine with `node@0.12.7`, but with `node@4.2.1` I get this:

```
"c:\mb\windows-builds-64\packages\node-mapnik\build\binding.sln" (default target) (1) ->
"c:\mb\windows-builds-64\packages\node-mapnik\build\action_after_build.vcxproj.metaproj" (default target) (2) ->
"c:\mb\windows-builds-64\packages\node-mapnik\build\mapnik.vcxproj.metaproj" (default target) (3) ->
"c:\mb\windows-builds-64\packages\node-mapnik\build\mapnik.vcxproj" (default target) (7) ->
(Link target) ->
  mapnik_vector_tile.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual void __cdecl std:: bad_cast::_Doraise(void)const " (__imp_?_Doraise@bad_cast@std@@MEBAXXZ) [c:\mb\windows-builds-64\packages\node-mapnik\build\mapni k.vcxproj]
  mapnik_vector_tile.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl std::bad_cast::bad_ca st(char const *)" (__imp_??0bad_cast@std@@QEAA@PEBD@Z) [c:\mb\windows-builds-64\packages\node-mapnik\build\mapnik.vcxproj]
  c:\mb\windows-builds-64\packages\node-mapnik\build\Release\mapnik.node : fatal error LNK1120: 2 unresolved externals [c:\mb\win dows-builds-64\packages\node-mapnik\build\mapnik.vcxproj]
```

**Comment by damylen** [comment]
Same here, are there any plans to support node4? I would like to integrate this with another program that requires node4.

**Comment by springmeyer** [comment]
@BergWerkGIS can you try it again? Those errors look like something unrelated to node-mapnik.

**Comment by BergWerkGIS** [comment]
Y, already tried yesterday. Getting some new strange errors like

```
mocha cannot be installed as a module of itself
```
when using self built `node.exe`.

When trying to use `nodejs`'s `node.exe`, `node-gyp` and/or `node-pre-gyp` fail to download the `node.lib` as the directory structure seems to have changed:

before:
```
..../v0.12.7/node.lib 
..../v0.12.7/x64/node.lib 
```

now:
```
..../v4.2.1/win-x86/node.lib 
..../v4.2.1/win-x64/node.lib 
```

see:
https://nodejs.org/dist/v4.2.1/

**Comment by BergWerkGIS** [comment]
Fresh build of `mapnik@master` and `node-mapnik@master` got me to the same error as in the original post.
Again, `node@0.12.7` works.

**Comment by BergWerkGIS** [comment]
Since we are building everything else with **`/MD`**, this seems to be the problem:

<pre>
"target_name": "vector_tile",
      <b>"type": "static_library",</b>
</pre>

https://github.com/mapnik/node-mapnik/blob/b4a88d29a025b9c34372d750e861321a1f35903c/binding.gyp#L48

`"type": "shared_library"` get's me past the previous error, but other changes to `binding.gyp` are needed, too.

**Comment by springmeyer** [comment]
Great findings, though odd this only comes up with 4.2.1. I wonder if 4.2.2 would be any different.

> but other changes to binding.gyp are needed, too.

What are you hitting?

**Comment by BergWerkGIS** [comment]
Error message is in first post.

Some hints:

* `/MT` vs. `/MD` https://social.msdn.microsoft.com/forums/vstudio/en-US/70cbb430-0a0c-4e04-8d1b-a036a03bba8a/link-error-2001unresolved-external-symbol
* could happen anywhere a dynamic cast is used, but that only applies during runtime http://stackoverflow.com/a/23391864

**Comment by BergWerkGIS** [comment]
ah, sorry, new message: `cannot find vector_tile.lib`

Already stumbled upon this when trying to build NET-Mapnik with latest mapnik at that time.
Also didn't find a solution, that's why it is commented: https://github.com/BergWerkGIS/NET-Mapnik/blob/8ea1d4d72ff0ea22bd91d1375483522ed5c6dcc4/NETMapnik.gyp#L25-L51

doing a `node@5.1.0` build ATM, will try node-mapnik with that.

**Comment by BergWerkGIS** [comment]
with `node@5.1.0`:
```
node-pre-gyp ERR! stack Error: Unsupported target version: 5.1.0
```

**Comment by springmeyer** [comment]
that can be fixed by running https://github.com/mapbox/node-pre-gyp/blob/master/scripts/abi_crosswalk.js and the committing to master and the pointing node-mapnik at node-pre-gyp master branch

**Comment by BergWerkGIS** [comment]
yeah, I just went back to `5.0.0` that's the last one in `abi_crosswalk.json`

**Comment by springmeyer** [comment]
as far as the vector_tile.lib issue don't know why it would not be found. but a quick workaround might be to add the .cc file to the list of sources that include the rest of the node c++ files. the reason i made it separate was just to be able to selectively suppress warnings.

**Comment by springmeyer** [comment]
@BergWerkGIS - just made a branch (https://github.com/mapnik/node-mapnik/compare/gyp-simplify) that should workaround that `vector_tile.lib` issue by avoiding its use. Can you see if this works with node 5?

**Comment by BergWerkGIS** [comment]
Still same problem with `gyp-simplify`.

```
"c:\mb\windows-builds-64\packages\node-mapnik\build\binding.sln" (default target) (1) ->
"c:\mb\windows-builds-64\packages\node-mapnik\build\action_after_build.vcxproj.metaproj" (default target) (2) ->
"c:\mb\windows-builds-64\packages\node-mapnik\build\mapnik.vcxproj.metaproj" (default target) (3) ->
"c:\mb\windows-builds-64\packages\node-mapnik\build\mapnik.vcxproj" (default target) (5) ->
(Link target) ->
  mapnik_vector_tile.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: virtual void __cdecl std:: bad_cast::_Doraise(void)const " (__imp_?_Doraise@bad_cast@std@@MEBAXXZ) [c:\mb\windows-builds-64\packages\node-mapnik\build\mapni k.vcxproj]
  mapnik_vector_tile.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl std::bad_cast::bad_ca st(char const *)" (__imp_??0bad_cast@std@@QEAA@PEBD@Z) [c:\mb\windows-builds-64\packages\node-mapnik\build\mapnik.vcxproj]
  c:\mb\windows-builds-64\packages\node-mapnik\build\Release\mapnik.node : fatal error LNK1120: 2 unresolved externals [c:\mb\win dows-builds-64\packages\node-mapnik\build\mapnik.vcxproj]
```

**Comment by springmeyer** [comment]
@BergWerkGIS how are you building node v5.1.0 exactly? Are you patching to build at all? Or are you using the v5.1.0 sources exactly with no modifications?

**Comment by BergWerkGIS** [comment]
@springmeyer still using v5.0.0 ATM
Tried with:
* same patches we had for 0.12.7
* without patches
* /MT
* /MD

always `bad_cast`

**Comment by BergWerkGIS** [comment]
node is built with `/MD`:

```
dumpbin node.exe /dependents
```

outputs

```
  Image has the following dependencies:

    WS2_32.dll
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-conio-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    WINMM.dll
    USER32.dll
    ADVAPI32.dll
    IPHLPAPI.DLL
    PSAPI.DLL
    USERENV.dll
```

This happens when the exe/libs use different C/C++ runtime libraries.
Ensure that the libraries and the exe are in sync (Project properties | C/C++ | Code Generation | Runtime Library).

**Comment by BergWerkGIS** [comment]
I think I found the problem, despite passing `--rootdir`

<pre>
gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--msvs_version=2015',
gyp verb cli   '--no-rollback',
gyp verb cli   '--target=5.0.0',
<b>gyp verb cli   '--rootdir=c:\\mb\\windows-builds-64\\packages\\node-v5.0.0-x64',</b>
gyp verb cli   '--module=c:\\mb\\windows-builds-64\\packages\\node-mapnik\\lib\\binding\\node-v47-win32-x64\\mapnik.node',
gyp verb cli   '--module_name=mapnik',
gyp verb cli   '--module_path=c:\\mb\\windows-builds-64\\packages\\node-mapnik\\lib\\binding\\node-v47-win32-x64',
gyp verb cli   '--msvs_version=2015' ]
</pre>

it looks like `node.lib` is being pulled from nodejs.org:

```
gyp verb created nodedir C:\Users\Administrator\.node-gyp
gyp http GET https://nodejs.org/download/release/v5.0.0/node-v5.0.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v5.0.0/node-v5.0.0-headers.tar.gz
```

```
gyp verb `node.lib` 32-bit url https://nodejs.org/download/release/v5.0.0/win-x86/node.lib
gyp verb `node.lib` 64-bit url https://nodejs.org/download/release/v5.0.0/win-x64/node.lib
gyp verb check download content checksum, need to download `SHASUMS256.txt`...
gyp verb checksum url https://nodejs.org/download/release/v5.0.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v5.0.0/SHASUMS256.txt
gyp verb streaming 32-bit node.lib to: C:\Users\Administrator\.node-gyp\5.0.0\ia32\node.lib
gyp http GET https://nodejs.org/download/release/v5.0.0/win-x86/node.lib
gyp verb streaming 64-bit node.lib to: C:\Users\Administrator\.node-gyp\5.0.0\x64\node.lib
gyp http GET https://nodejs.org/download/release/v5.0.0/win-x64/node.lib
```

**Comment by BergWerkGIS** [comment]
It's `--nodedir`, **not** `--rootdir`.
Still, same error.

**Comment by springmeyer** [comment]
Solved by https://github.com/mapbox/node/commit/128c968fb5d79d67c5740aff03ee8fb30e159e88

**Comment by springmeyer** [comment]
Followups at https://github.com/nodejs/node/pull/258

**Comment by BergWerkGIS** [comment]
Still doesn't work for me locally:

* neither by building `node` myself via https://github.com/mapbox/node-cpp11
* nor using the precompiled `mapbox node`
* nor `node-mapnik@master` or `node-mapnik@simplify-gyp`

Same error `bad_cast`.

Maybe this is due to the updated mapnik dependencies.
Going to try with the mapnik sdk used by AppVeyor builds next.

**Comment by BergWerkGIS** [comment]
"Fixed" it by using the same scripts locally as on AppVeyor.

**Comment by damylen** [comment]
I tried 'npm install mapnik@3.x' with node v4.2.2 with the latest NPM versions (both 2 & 3) on a Windows 7 machine.. It doesn't seem to work. I'm getting the following error message:

Failed at the mapnik@3.4.11 install script 'node-pre-gyp install --fallback-to-build'

Any suggestions?

**Comment by BergWerkGIS** [comment]
@damylen `npm install` tries to build `node-mapnik` from source, but your system is not setup to do so.

Currently we provide prebuilt binary packages for node 0.10.40, 0.12.7 and 5.1.0.
(can be seen here: https://github.com/mapnik/node-mapnik/blob/master/appveyor.yml#L9-L29)

If you match your node version to one of those `npm install` should work.
